<a href="https://colab.research.google.com/github/Sushmapurella13/AIML/blob/main/2303A52188%20AIML-ASGN1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [5]:
import numpy as np
import pandas as pd

a=[1,3,4,5,2,3]
print(a)
print(np.array(a))
print(pd.array(a))
print(type(a))


[1, 3, 4, 5, 2, 3]
[1 3 4 5 2 3]
<IntegerArray>
[1, 3, 4, 5, 2, 3]
Length: 6, dtype: Int64
<class 'list'>


In [18]:
s=[2,4,5,6,7]
b=[2,5,7,8,4]
import numpy as np
m=np.array(s)
v=np.array(b)
print(m*v)
print(m/v)
print(np.power(m,v))
print(m+v)
print("subtraction:",m-v)

[ 4 20 35 48 28]
[1.         0.8        0.71428571 0.75       1.75      ]
[      4    1024   78125 1679616    2401]
[ 4  9 12 14 11]
subtraction: [ 0 -1 -2 -2  3]


In [17]:
print(np.sin(90))
print(np.cos(90))
print(np.tan(90))
print(np.log(10))
print(np.log2(10))
print(np.exp(10))

0.8939966636005579
-0.4480736161291701
-1.995200412208242
2.302585092994046
3.321928094887362
22026.465794806718
